### ISSUE TITLE
Ribbon Implementation Does not Support "https" when using Eureka / Service Discovery

### ISSUE THREAD

**Issue by gmcouto** [PlaytikaOSS/feign-reactive#230]
I had added reactive-feign to one of our most important micro-services in here, and we are using Eureka for Service Discovery.
All of our services register itself as only secure ports being enabled... and feign-reactive picks the `443` ports right away. However, it is still making calls using `http` scheme when using Ribbon (Cloud module).

We are unable to bump this microservice to Spring Boot 2.2, so we are still using Spring Boot 2.1 and cannot use Cloud 2 implementation that takes schema into account.

The current implementation for Ribbon in the cloud module is 
```
  protected ReactiveHttpRequest loadBalanceRequest(ReactiveHttpRequest request, Server server) {
    URI lbUrl =
        UriComponentsBuilder.fromUri(request.uri())
            .host(server.getHost())
            .port(server.getPort())
            .build(true)
            .toUri();
    return new ReactiveHttpRequest(request, lbUrl);
```
So it uses the schema received from the `ReactiveFeignClientFactoryBean` that is hardcoded to use http only.

I can provide a PR that will take Eureka data into consideration and use it as the schema for this code.

**Comment by gmcouto** [comment]
PR is sent

**Comment by p4pramod** [comment]
Hi can you let me know which version of Feign Reactor WebClient has this fix?

**Comment by kptfh** [comment]
Reactive Feign client doesn't support Ribbon now, so will close issue. 
Please create new ticket for Spring ReactiveLoadBalancer if it's still reproducible.
