### ISSUE TITLE
gzip compression support

### ISSUE THREAD

**Issue by Laess3r** [PlaytikaOSS/feign-reactive#466]
Hi! 
Is it possible to enable gzip compression support?

```
HttpClient httpClient = HttpClient.create().compress(true);
    final WebClient.Builder webClient = WebClient.builder()
        .clientConnector(new ReactorClientHttpConnector(httpClient))
        .exchangeStrategies(ExchangeStrategies.builder()
            .codecs(configurer -> configurer
                .defaultCodecs()
                .maxInMemorySize(32 * 1024 * 1024))
            .build());
WebReactiveFeign.builder(webClient).target(....

```
I tried to use httpClient with compression, but this does not seem to enable any compression, the ReactiveHttpResponse does not contain a Content-Encoding header.

**Comment by kptfh** [comment]
Try to configure compression via `ReactiveOptions`

**Comment by reneeshr** [comment]
Hey @kptfh 

I tried to pass the `acceptCompressed` flag in the ReactiveOptions for my reactive feign client and it doesn't include the `Accept-Encoding:gzip` header automatically with the request.

Then I tried to add a client connector to compress the request according to [this](https://stackoverflow.com/questions/53939724/decode-content-encoding-gzip-using-spring-webclient/53958076#53958076) link, but this is not passing the `Accept-Encoding:gzip` header while making API request in microservice.


> 

```
WebReactiveFeign.builder(
            WebClient.builder()
                .clientConnector(
                    ReactorClientHttpConnector(
                        HttpClient.create()
                            .compress(reactiveClientProperties.acceptCompressed).secure()
                    )
                )
        )
 ```
        
Finally, I added the `Accept-Encoding` header in the FeignApi client method to see if it can accept the compressed response from the server like below

 ```
 @Headers("Content-Type: text/html", "Accept: text/html", "Accept-Encoding: gzip")
 @RequestLine("GET /api/v1/tickets/{ticketId}/render/html")
 ```
   
When I enable it, I can see the Accept-Encoding headers are passing while invoking another API, however, the response headers don't contain the `Content-Encoding: gzip` headers, even though the server is working as expected when we test with Postman as I can see the headers are coming correctly in the response.

Could you please advise if we are missing something to enable compression on the client side for reactive? I have attached the API request/response headers trace for your reference.

```
[Client#apiMethod(String)] REQUEST HEADERS
Accept:[text/html]
Accept-Encoding:[gzip]
Content-Type:[text/html]
Authorization:[Basic xxxxxxxxxxxxx==]
X-MYT-REQUEST-ID:[aaa05595-8d17-55ec-8d54-c3746ccfdf5a]
User-Agent:[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36]
x-forwarded-for:[1000000.0000.00000]
Accept-Language:[en]

[Client#apiMethod(String)]  RESPONSE HEADERS
Cache-Control:no-cache, max-age=0, must-revalidate
Content-Type:text/html
Etag:40-xxxxxxxxxxxxxxxxxxxxxxxxx
Expires:0
Pragma:no-cache
Referrer-Policy:no-referrer
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-Myt-Request-Id:xxxxxxxxxxxxxxxxxxxxxxxxx
X-Xss-Protection:1 ; mode=block
Date:Fri, 21 Apr 2023 08:43:57 GMT
transfer-encoding:chunked
```
