### ISSUE TITLE
Using a custom response decoder

### ISSUE THREAD

**Issue by jaume-pinyol** [PlaytikaOSS/feign-reactive#467]
Hi!, 
I have a quick question, I've been looking and looking but is there a way to pass your own custom response decoder using the spring configuration?

In feign I used to do it like:
```java
 @Bean
  public Decoder feignDecoder(...) {  
   return new MyCustomDecoder(...);
  }
  ```
But I'm not finding the way to do it in reactive feign.
 
Regards

**Comment by jaume-pinyol** [comment]
Just if someone is interested, if using the webreactiveclient, a WebclientFeignCustomizer can be used.

```
 @Bean
  public WebClientFeignCustomizer customizer(ObjectMapper objectMapper) {
    return (client) -> {
      client.codecs((configurer) -> {
        configurer.customCodecs().register(new CustomReader<>());
      });
    };
  }

**Comment by kptfh** [comment]
Will need to check if there is more obvious way to configure decoder
