### ISSUE TITLE
ReactiveHttpRequestInterceptors missing update/remove headers feature for updating AUTHORIZATION access token value

### ISSUE THREAD

**Issue by guravamey** [PlaytikaOSS/feign-reactive#483]
I have added an Interceptor which appends access token for every request. 

`@Bean
  public ReactiveHttpRequestInterceptor apiKeyInterceptor() {
    return ReactiveHttpRequestInterceptors.addHeader(
        HttpHeaders.AUTHORIZATION, String.format("%s %s", BEARER.getValue(), getAccessToken()));
  }`

If a request fails due to any error, the circuit breaker tries to retry the request. While retrying, it reinitialises the bean which calls ReactiveHttpRequestInterceptors.addHeader. Since this method is static, the header values keep on duplicating for every retry.

I also need to update the interceptor AUTHORIZATION header for new token.

As ReactiveHttpRequestInterceptors class does not provide any method to remove/update headers, I am stuck with this problem

Any thoughts ?

Thanks :)

**Comment by KamaniAman** [comment]
@guravamey how did you resolve this issue? I am also having similar scenario
