### ISSUE TITLE
Exception is not porpagated for nonretryable exception when retry policy is used.

### ISSUE THREAD

**Issue by OlPochuiev** [PlaytikaOSS/feign-reactive#492]
Hello there!

I use the retry policy and custom error handling for specific status codes. I expect that exception, which is thrown in `ErrorDecoder`, should be propagated to the top level, but `OutOfRetriesException` wrapped the original exception instead. The exception in ErrorDecoder is non-retryable.
We are using feign version `3.2.4`
Our config looks like this:
```
@Bean
fun reactiveRetryPolicy(): ReactiveRetryPolicy {
    return BasicReactiveRetryPolicy.retry(retries)
}
```
```
@Bean
fun customErrorDecoder() = ErrorDecoder { methodKey, response ->
    if (HttpStatus.NOT_FOUND.value() == response?.status()) {
        return@ErrorDecoder BusinessException()
    }
    return@ErrorDecoder ErrorDecoder.Default().decode(methodKey, response)
}
```
Also, I tried to use `ReactiveErrorMapper`. Without success. Config is here:
```
@Bean
fun buildNotFoundErrorMapper() = ReactiveErrorMapper { _, u ->
    if (u is FeignException.NotFound) {
        return@ReactiveErrorMapper AppNotInstalledException()
    }
    return@ReactiveErrorMapper u
}
```
In non reactive feign there is posibility to use `exceptionPropagationPolicy()`
Could it be added to reactive feign as well?

**Comment by kptfh** [comment]
It's not clear for me what exactly fix do you want:
  - do not retry on nonretryable exception?
  - unwrap  OutOfRetriesException  in case of exceptionPropagationPolicy.UNWRAP  ?

**Comment by OlPochuiev** [comment]
Hi @kptfh !
I would expect to unwrap OutOfRetriesException in case of exceptionPropagationPolicy.UNWRAP.
Regarding point 1, if I remember it correctly, if the exception is nonretryable, the lib already makes only one attempt and throws an exception.

**Comment by kptfh** [comment]
Please check this pr https://github.com/PlaytikaOSS/feign-reactive/pull/571
and especially  [this test](https://github.com/PlaytikaOSS/feign-reactive/pull/571/files#diff-4f1bd3639c5430884e13c166ef7242ab8493c3e9b92517534c4459f4a5e54c3dR191)

BTW: Reactive feign uses 'RetryableException' only to detect correct retry delay in 'BasicReactiveRetryPolicy'

[https://github.com/PlaytikaOSS/feign-reactive/blob/develop/feign-reactor-core/src/main/java/reactivefeign/retry/BasicReactiveRetryPolicy.java#L58](BasicReactiveRetryPolicy)

If retry policy was set it will retry on all errors
If you want to skip retries for specific error then you need to use 'FilteredReactiveRetryPolicy'

**Comment by OlPochuiev** [comment]
Amazing! Looks like it :) Thanks.

Thanks for explaining
