### ISSUE TITLE
can't configure feign reactive with java 17 and spring boot 3.0.0 

### ISSUE THREAD

**Issue by battosaai** [PlaytikaOSS/feign-reactive#534]
![image](https://user-images.githubusercontent.com/103481878/213140230-56e0d7ab-3f87-4997-ab6d-3c7b1cec8053.png)
cannot create bean

<dependency>
            <groupId>com.playtika.reactivefeign</groupId>
            <artifactId>feign-reactor-spring-cloud-starter</artifactId>
            <version>3.2.6</version>
        </dependency>

**Comment by wllianwd** [comment]
Spring Boot 3 is not supported yet.
Here a PR: https://github.com/PlaytikaOSS/feign-reactive/pull/539

**Comment by kptfh** [comment]
After all issues get fixed and the last release of RF library with support of SB2 we will switch to SB3
Just started fixing issues ))

**Comment by kptfh** [comment]
please check 4.0.0
